import hashlib
import math
import uuid
from typing import Any, Dict, List


def generate_deterministic_embedding(text: str, category_slug: str, dim: int = 1536) -> List[float]:
    """
    Generates a deterministic 1536-dimensional unit vector for seed products.
    Ensures that products within the same category/cluster share strong cosine similarity
    while maintaining distinct item-level traits for query matching in local offline mode.
    """
    vec = [0.0] * dim

    # Category cluster anchor (defines base directional bias)
    cat_hash = int(hashlib.sha256(category_slug.encode("utf-8")).hexdigest(), 16)
    for i in range(dim):
        cat_val = math.sin((cat_hash + i * 37) % 10000)
        vec[i] += cat_val * 0.65

    # Text token variance (item specific characteristics)
    words = text.lower().split()
    for word_idx, word in enumerate(words):
        w_hash = int(hashlib.md5(word.encode("utf-8")).hexdigest(), 16)
        slot = (w_hash + word_idx) % dim
        vec[slot] += 0.35 * math.cos(w_hash % 1000)

    # L2 normalize vector so norm(vec) == 1.0 (cosine similarity == dot product)
    norm = math.sqrt(sum(x * x for x in vec))
    if norm > 0:
        vec = [round(x / norm, 6) for x in vec]
    return vec


# 8 Categories
CATEGORIES: List[Dict[str, Any]] = [
    {
        "id": "c1000000-0000-0000-0000-000000000001",
        "name": "Audio & Wearables",
        "slug": "audio-wearables",
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Headphones",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000002",
        "name": "Workspace & Tech",
        "slug": "workspace-tech",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Laptop",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000003",
        "name": "Fitness & Activewear",
        "slug": "fitness-activewear",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Dumbbell",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000004",
        "name": "Specialty Coffee & Kitchen",
        "slug": "specialty-coffee-kitchen",
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Coffee",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000005",
        "name": "Bags & Commute",
        "slug": "bags-commute",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Briefcase",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000006",
        "name": "Smart Living",
        "slug": "smart-living",
        "image_url": "https://images.unsplash.com/photo-1558002038-1055907df827?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Home",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000007",
        "name": "Outdoors & Expedition",
        "slug": "outdoors-expedition",
        "image_url": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Compass",
    },
    {
        "id": "c1000000-0000-0000-0000-000000000008",
        "name": "Wellness & Grooming",
        "slug": "wellness-grooming",
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80",
        "icon_name": "Sparkles",
    },
]

# 10 Businesses
BUSINESSES: List[Dict[str, Any]] = [
    {
        "id": "b1000000-0000-0000-0000-000000000001",
        "name": "Aura Acoustics",
        "slug": "aura-acoustics",
        "description": "Pioneering studio-grade wireless sound engineering, acoustic dampening materials, and active noise-cancellation audio gear designed for audiophiles and active professionals.",
        "logo_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1511671782779-c97d3d27a1d4?w=1200&auto=format&fit=crop&q=80",
        "category": "Audio & Electronics",
        "rating": 4.9,
        "location": "San Francisco, CA",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000002",
        "name": "Nordic Ergonomics",
        "slug": "nordic-ergonomics",
        "description": "Minimalist Scandinavian workstation architecture crafted from sustainable European hardwoods and aircraft-grade aluminum.",
        "logo_url": "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=1200&auto=format&fit=crop&q=80",
        "category": "Workspace & Furniture",
        "rating": 4.8,
        "location": "Seattle, WA",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000003",
        "name": "Apex Kinetics",
        "slug": "apex-kinetics",
        "description": "Biomechanically engineered training apparel and elite gym equipment designed to maximize athletic recovery and performance output.",
        "logo_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=1200&auto=format&fit=crop&q=80",
        "category": "Sports & Fitness",
        "rating": 4.7,
        "location": "Austin, TX",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000004",
        "name": "Origin Roastworks",
        "slug": "origin-roastworks",
        "description": "Single-origin micro-lot roasters and precision manual espresso extraction tools built for serious coffee craftspeople.",
        "logo_url": "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1442512595331-e89e73853f31?w=1200&auto=format&fit=crop&q=80",
        "category": "Coffee & Kitchen",
        "rating": 4.95,
        "location": "Portland, OR",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000005",
        "name": "Vanguard Carry Goods",
        "slug": "vanguard-carry-goods",
        "description": "Tactical urban backpacks, weatherproof travel duffels, and modular EDC slings tested across 40 countries.",
        "logo_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1473186578172-c141e6798cf4?w=1200&auto=format&fit=crop&q=80",
        "category": "Luggage & Carry",
        "rating": 4.85,
        "location": "Brooklyn, NY",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000006",
        "name": "Lumina Ambient Living",
        "slug": "lumina-ambient-living",
        "description": "Circadian biological lighting fixtures and smart architectural home automation for calm and focus.",
        "logo_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1513694203232-719a280e022f?w=1200&auto=format&fit=crop&q=80",
        "category": "Smart Home",
        "rating": 4.75,
        "location": "San Jose, CA",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000007",
        "name": "Terra Wilds Equipment",
        "slug": "terra-wilds-equipment",
        "description": "Ultralight titanium trail systems, packable solar power grids, and thermal expedition gear.",
        "logo_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=1200&auto=format&fit=crop&q=80",
        "category": "Outdoor & Adventure",
        "rating": 4.8,
        "location": "Boulder, CO",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000008",
        "name": "Solace Botanicals",
        "slug": "solace-botanicals",
        "description": "Clinical cold-pressed botanical skin formulations, restorative adaptogenic tonics, and zero-waste self-care essentials.",
        "logo_url": "https://images.unsplash.com/photo-1608248597359-009710f63b8d?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=1200&auto=format&fit=crop&q=80",
        "category": "Personal Care",
        "rating": 4.9,
        "location": "Los Angeles, CA",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000009",
        "name": "Kanso Tech Lab",
        "slug": "kanso-tech-lab",
        "description": "Custom CNC-milled aluminum mechanical keyboards, magnetic cable management, and enthusiast desk hardware.",
        "logo_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1618384887929-16ec33fab9ef?w=1200&auto=format&fit=crop&q=80",
        "category": "Computer Peripherals",
        "rating": 4.85,
        "location": "Chicago, IL",
    },
    {
        "id": "b1000000-0000-0000-0000-000000000010",
        "name": "Verdant Culinary",
        "slug": "verdant-culinary",
        "description": "Forged multi-layer Damascus steel cutlery, seasoned cast iron cookware, and artisan kitchen tools.",
        "logo_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=200&auto=format&fit=crop&q=80",
        "banner_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=1200&auto=format&fit=crop&q=80",
        "category": "Culinary & Kitchen",
        "rating": 4.92,
        "location": "Nashville, TN",
    },
]

# 52 Realistic, High-Fidelity Products with Meaningful Specs & Descriptions
PRODUCTS_RAW: List[Dict[str, Any]] = [
    # --- Category 1: Audio & Wearables (Aura Acoustics) ---
    {
        "name": "Aura Flow ANC Wireless Headphones",
        "slug": "aura-flow-anc-wireless-headphones",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 149.00,
        "rating": 4.9,
        "stock_quantity": 45,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
        "description": "Hybrid active noise-cancelling wireless over-ear headphones with 40mm beryllium drivers, IPX4 sweat resistance, and 38-hour battery life. Perfect for intense gym workouts, daily subway commuting, and focus sessions. Features plush breathable memory foam earcups and zero-latency Bluetooth 5.3 multipoint pairing.",
    },
    {
        "name": "Aura Pulse Pro Sport Earbuds",
        "slug": "aura-pulse-pro-sport-earbuds",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 89.00,
        "rating": 4.75,
        "stock_quantity": 80,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1590658268037-6bf12165a8df?w=800&auto=format&fit=crop&q=80",
        "description": "True wireless workout earbuds with ergonomic wingtips that lock comfortably during sprinting and HIIT. IP68 certified dust and waterproof, dynamic bass boost mode, transparency passthrough for outdoor running safety, and 24 hours of playback with the compact wireless charging case.",
    },
    {
        "name": "Aura Studio Reference One Monitor",
        "slug": "aura-studio-reference-one-monitor",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 329.00,
        "rating": 4.95,
        "stock_quantity": 18,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
        "description": "Bi-amplified desktop studio monitor featuring a 5-inch woven Kevlar woofer and 1-inch silk dome tweeter. Delivers flat frequency response (45Hz - 22kHz) for music producers, audio engineers, and discerning audiophiles seeking transparent mixing precision.",
    },
    {
        "name": "Aura Clarity USB-C Conference Mic",
        "slug": "aura-clarity-usbc-conference-mic",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 119.00,
        "rating": 4.8,
        "stock_quantity": 35,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1583778176476-4a8b02a64c01?w=800&auto=format&fit=crop&q=80",
        "description": "Studio condenser microphone with triple capsule array, cardioid/omnidirectional pickup patterns, hardware touch-to-mute, and onboard DSP noise suppression. Built for crisp remote work conference calls, podcasting, and voiceover streaming.",
    },
    {
        "name": "Aura Pocket DAC Amp",
        "slug": "aura-pocket-dac-amp",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 79.00,
        "rating": 4.65,
        "stock_quantity": 60,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800&auto=format&fit=crop&q=80",
        "description": "Ultra-compact 32-bit/384kHz ES9281AC Pro DAC and headphone amplifier with 3.5mm and 4.4mm balanced outputs. Powers high-impedance headphones from your smartphone or laptop with zero harmonic distortion.",
    },

    # --- Category 2: Workspace & Tech (Nordic Ergonomics & Kanso Tech Lab) ---
    {
        "name": "Nordic Ergo-Lift Standing Desk",
        "slug": "nordic-ergo-lift-standing-desk",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 549.00,
        "rating": 4.92,
        "stock_quantity": 14,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
        "description": "Dual-motor motorized standing desk featuring a solid 60x30 inch FSC-certified birch wood tabletop. Whisper-quiet lifting columns (<42dB), 4 programmable height memory presets, integrated power strip under-tray, and anti-collision safety sensors.",
    },
    {
        "name": "Nordic SpineAlign Ergonomic Chair",
        "slug": "nordic-spinealign-ergonomic-chair",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 420.00,
        "rating": 4.88,
        "stock_quantity": 22,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1580481077195-c3a821a58875?w=800&auto=format&fit=crop&q=80",
        "description": "Dynamic lumbar support task chair with breathable elastomeric mesh backrest, 4D adjustable armrests, seat pan depth slider, and pneumatic gas lift. Supports all-day upright posture for desk workers and programmers.",
    },
    {
        "name": "Nordic Walnut Dual Monitor Stand",
        "slug": "nordic-walnut-dual-monitor-stand",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 95.00,
        "rating": 4.85,
        "stock_quantity": 50,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
        "description": "Elevated desk shelf crafted from hand-finished American Walnut with matte black steel feet and natural cork padding. Elevates dual 27-inch monitors to eye level while storing full-sized keyboards and docking stations underneath.",
    },
    {
        "name": "Nordic Merino Wool Desk Mat",
        "slug": "nordic-merino-wool-desk-mat",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 45.00,
        "rating": 4.7,
        "stock_quantity": 90,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1616440347437-b1c73416efc2?w=800&auto=format&fit=crop&q=80",
        "description": "Extra-large (35x16 inch) natural felted Merino wool desk blotter with non-slip organic rubber base. Soft, sound-dampening surface provides comfortable wrist support and smooth optical mouse tracking.",
    },
    {
        "name": "Kanso 75 CNC Mechanical Keyboard",
        "slug": "kanso-75-cnc-mechanical-keyboard",
        "business_slug": "kanso-tech-lab",
        "category_slug": "workspace-tech",
        "price": 185.00,
        "rating": 4.94,
        "stock_quantity": 28,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
        "description": "Anodized aluminum 75% layout custom mechanical keyboard with gasket mount, factory-lubricated Gateron Oil King linear switches, PBT dye-sub keycaps, per-key RGB, and VIA/QMK programmable firmware for Mac and Windows.",
    },
    {
        "name": "Kanso Aviator Coiled USB-C Cable",
        "slug": "kanso-aviator-coiled-usbc-cable",
        "business_slug": "kanso-tech-lab",
        "category_slug": "workspace-tech",
        "price": 32.00,
        "rating": 4.6,
        "stock_quantity": 110,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1563770660941-20978e870e26?w=800&auto=format&fit=crop&q=80",
        "description": "Double-sleeved Paracord and Techflex coiled mechanical keyboard cable with detachable GX16 5-pin metal aviator connector. Ultra-durable tight coils designed for clean desk aesthetics.",
    },

    # --- Category 3: Fitness & Activewear (Apex Kinetics) ---
    {
        "name": "Apex Pace Carbon Marathon Running Shoe",
        "slug": "apex-pace-carbon-marathon-running-shoe",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 180.00,
        "rating": 4.88,
        "stock_quantity": 32,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
        "description": "Elite distance road racing shoe featuring a curved full-length carbon fiber propulsion plate, supercritical nitrogen-infused foam midsole, and ultralight breathable engineered monomesh upper. Weighs only 7.2 oz.",
    },
    {
        "name": "Apex IronCast Adjustable Dumbbell Pair",
        "slug": "apex-ironcast-adjustable-dumbbell-pair",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 289.00,
        "rating": 4.85,
        "stock_quantity": 16,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1583454110551-21f2fa2afe61?w=800&auto=format&fit=crop&q=80",
        "description": "Space-saving compact selectorized dumbbell system adjusting from 5 lbs to 52.5 lbs per hand with a single twist of the textured knurled steel handle. Replaces 15 sets of weights for home gym strength workouts.",
    },
    {
        "name": "Apex AeroFlex Compression Tights",
        "slug": "apex-aeroflex-compression-tights",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 64.00,
        "rating": 4.7,
        "stock_quantity": 65,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1506629082955-511b1aa562c8?w=800&auto=format&fit=crop&q=80",
        "description": "Graduated compression athletic tights with 4-way stretch fabric, targeted quadricep and calf muscle stabilization, bonded flatlock chafe-free seams, and a moisture-wicking zippered phone holster.",
    },
    {
        "name": "Apex Velocity Percussive Massage Gun",
        "slug": "apex-velocity-percussive-massage-gun",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 115.00,
        "rating": 4.82,
        "stock_quantity": 40,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1518611012118-696072aa579a?w=800&auto=format&fit=crop&q=80",
        "description": "Deep-tissue brushless motor recovery massager delivering 12mm stroke amplitude, 5 calibrated speed settings (1600 - 3200 RPM), 6 interchangeable therapy heads, and whisper-quiet QuietGlide damping.",
    },
    {
        "name": "Apex Natural Cork High-Grip Yoga Mat",
        "slug": "apex-natural-cork-high-grip-yoga-mat",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 58.00,
        "rating": 4.78,
        "stock_quantity": 55,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1592432678016-e910b452f9a2?w=800&auto=format&fit=crop&q=80",
        "description": "Organic Portuguese cork and natural tree rubber exercise mat. The grip increases with sweat and humidity during hot yoga and calisthenics. Naturally antimicrobial and 5mm thick for optimal joint cushioning.",
    },

    # --- Category 4: Specialty Coffee & Kitchen (Origin Roastworks & Verdant Culinary) ---
    {
        "name": "Origin Precision Conical Burr Coffee Grinder",
        "slug": "origin-precision-conical-burr-coffee-grinder",
        "business_slug": "origin-roastworks",
        "category_slug": "specialty-coffee-kitchen",
        "price": 195.00,
        "rating": 4.95,
        "stock_quantity": 20,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
        "description": "Zero-retention single-dose coffee grinder featuring 48mm Italian stainless steel conical burrs, stepless micrometric grind adjustment for espresso through French press, and anti-static ionizer.",
    },
    {
        "name": "Origin Smart Gooseneck Pour-Over Kettle",
        "slug": "origin-smart-gooseneck-pour-over-kettle",
        "business_slug": "origin-roastworks",
        "category_slug": "specialty-coffee-kitchen",
        "price": 135.00,
        "rating": 4.89,
        "stock_quantity": 38,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1520970014086-2208d157c9e2?w=800&auto=format&fit=crop&q=80",
        "description": "Electric 0.9L variable temperature kettle with counterbalanced ergonomic handle, precision pour spout for laminar flow control, LCD digital temperature hold (104°F - 212°F), and integrated brew timer.",
    },
    {
        "name": "Origin Yirgacheffe Single-Origin Whole Beans (2lb)",
        "slug": "origin-yirgacheffe-single-origin-whole-beans-2lb",
        "business_slug": "origin-roastworks",
        "category_slug": "specialty-coffee-kitchen",
        "price": 38.00,
        "rating": 4.92,
        "stock_quantity": 85,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1559056199-641a0ac8b55e?w=800&auto=format&fit=crop&q=80",
        "description": "Washed heirloom Ethiopian specialty coffee freshly roasted to light-medium perfection. Delicate cupping profile with floral jasmine aromatics, vibrant bergamot citrus notes, and sweet honeysuckle finish.",
    },
    {
        "name": "Verdant Damascus 8-Inch Chef Knife",
        "slug": "verdant-damascus-8-inch-chef-knife",
        "business_slug": "verdant-culinary",
        "category_slug": "specialty-coffee-kitchen",
        "price": 145.00,
        "rating": 4.96,
        "stock_quantity": 25,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1590794056226-79ef3a8147e1?w=800&auto=format&fit=crop&q=80",
        "description": "Hand-forged 67-layer Japanese VG-10 Damascus steel blade cryogenically treated to 60±2 HRC hardness. Razor-sharp 15-degree edge bevel with an ergonomic vacuum-treated dark pakkawood handle.",
    },
    {
        "name": "Verdant Seasoned Cast Iron Skillet 12-Inch",
        "slug": "verdant-seasoned-cast-iron-skillet-12-inch",
        "business_slug": "verdant-culinary",
        "category_slug": "specialty-coffee-kitchen",
        "price": 75.00,
        "rating": 4.88,
        "stock_quantity": 42,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1584990347449-399d8d641ea5?w=800&auto=format&fit=crop&q=80",
        "description": "Heavyweight pre-seasoned cast iron skillet featuring a hand-polished smooth cooking surface for effortless non-stick searing. Suitable for induction, gas, campfire, and oven baking up to 550°F.",
    },

    # --- Category 5: Bags & Commute (Vanguard Carry Goods) ---
    {
        "name": "Vanguard Shift 26L Commuter Backpack",
        "slug": "vanguard-shift-26l-commuter-backpack",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 98.00,
        "rating": 4.91,
        "stock_quantity": 55,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
        "description": "Weatherproof 840D Cordura ballistic nylon daypack with dedicated suspended 16-inch laptop compartment, hidden passport security pocket, magnetic Fidlock buckle closures, and luggage trolley pass-through.",
    },
    {
        "name": "Vanguard Tech Sling 7L",
        "slug": "vanguard-tech-sling-7l",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 62.00,
        "rating": 4.79,
        "stock_quantity": 70,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80",
        "description": "Minimalist crossbody sling bag with waterproof YKK Aquaguard zippers, fleece-lined 11-inch iPad sleeve, internal cable elastic loops, and quick-release reversible shoulder strap.",
    },
    {
        "name": "Vanguard Overnighter Weekender Duffel 42L",
        "slug": "vanguard-overnighter-weekender-duffel-42l",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 139.00,
        "rating": 4.86,
        "stock_quantity": 30,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1548036328-c9fa89d128fa?w=800&auto=format&fit=crop&q=80",
        "description": "TSA carry-on compliant travel duffel featuring an isolated ventilated shoe compartment, padded shoulder strap, water-resistant bottom tarp, and interior modular compression straps.",
    },
    {
        "name": "Vanguard Slim Italian Leather Cardholder",
        "slug": "vanguard-slim-italian-leather-cardholder",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 38.00,
        "rating": 4.72,
        "stock_quantity": 95,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1627123424574-724758594e93?w=800&auto=format&fit=crop&q=80",
        "description": "Vegetable-tanned full-grain Italian leather bifold card sleeve with RFID blocking lining. Holds 8 cards plus folded cash while maintaining an ultra-thin 6mm profile in front pockets.",
    },

    # --- Category 6: Smart Living (Lumina Ambient Living) ---
    {
        "name": "Lumina Halo Circadian Sunrise Lamp",
        "slug": "lumina-halo-circadian-sunrise-lamp",
        "business_slug": "lumina-ambient-living",
        "category_slug": "smart-living",
        "price": 129.00,
        "rating": 4.87,
        "stock_quantity": 36,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
        "description": "Smart biological bedside light simulating natural dawn progression and sunset twilight. Clinically tuned 98+ CRI LEDs stimulate morning cortisol and evening melatonin. Compatible with Apple HomeKit, Google Home, and Matter.",
    },
    {
        "name": "Lumina PureFlow HEPA Air Purifier",
        "slug": "lumina-pureflow-hepa-air-purifier",
        "business_slug": "lumina-ambient-living",
        "category_slug": "smart-living",
        "price": 165.00,
        "rating": 4.9,
        "stock_quantity": 25,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1585771724684-38269d6639fd?w=800&auto=format&fit=crop&q=80",
        "description": "True H13 Medical-Grade HEPA filtration capturing 99.97% of airborne allergens, pollen, dust, and PM2.5 smoke. Whisper-quiet 20dB sleep mode with laser air quality sensor and ambient ring indicator for 500 sq ft rooms.",
    },
    {
        "name": "Lumina Ultrasonic Ceramic Diffuser",
        "slug": "lumina-ultrasonic-ceramic-diffuser",
        "business_slug": "lumina-ambient-living",
        "category_slug": "smart-living",
        "price": 54.00,
        "rating": 4.75,
        "stock_quantity": 60,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1608248597359-009710f63b8d?w=800&auto=format&fit=crop&q=80",
        "description": "Handcrafted matte ceramic stone essential oil diffuser with 2.4MHz ultrasonic misting, ambient amber glow nightlight, and automatic shut-off safety sensor.",
    },
    {
        "name": "Lumina Smart Temperature Sensing Mug",
        "slug": "lumina-smart-temperature-sensing-mug",
        "business_slug": "lumina-ambient-living",
        "category_slug": "smart-living",
        "price": 99.00,
        "rating": 4.65,
        "stock_quantity": 48,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1517256064527-09c73fc73e38?w=800&auto=format&fit=crop&q=80",
        "description": "14 oz ceramic coated stainless steel self-heating smart mug. Keeps your coffee or tea at your exact preferred drinking temperature (120°F - 145°F) for up to 3 hours on battery, or all day on the included coaster.",
    },

    # --- Category 7: Outdoors & Expedition (Terra Wilds Equipment) ---
    {
        "name": "Terra Ultralight Titanium Solo Stove",
        "slug": "terra-ultralight-titanium-solo-stove",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 48.00,
        "rating": 4.84,
        "stock_quantity": 75,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800&auto=format&fit=crop&q=80",
        "description": "Folding backpacking stove crafted from Grade 1 aerospace titanium. Weighs only 48 grams, boils 500ml of water in 3 minutes 10 seconds, and packs down flat into the palm of your hand.",
    },
    {
        "name": "Terra Alpine 2-Person Ultralight Tent",
        "slug": "terra-alpine-2-person-ultralight-tent",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 310.00,
        "rating": 4.92,
        "stock_quantity": 15,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80",
        "description": "Silnylon 15D seam-taped 3-season freestanding backpacking shelter with DAC Featherlite aluminum poles, dual vestibules, and stargazing mesh canopy. Total trail weight under 2.4 lbs.",
    },
    {
        "name": "Terra Solar Expedition 24W Power Panel",
        "slug": "terra-solar-expedition-24w-power-panel",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 78.00,
        "rating": 4.76,
        "stock_quantity": 40,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1509395062183-67c5ad6faff9?w=800&auto=format&fit=crop&q=80",
        "description": "Foldable monocrystalline solar panel charger with 24% conversion efficiency, dual USB-C Power Delivery ports, weather-resistant ETFE laminate, and carabiner loops for charging on your backpack while hiking.",
    },
    {
        "name": "Terra Vacuum Insulated Water Canteen 32oz",
        "slug": "terra-vacuum-insulated-water-canteen-32oz",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 36.00,
        "rating": 4.89,
        "stock_quantity": 90,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1602143407151-7111542de6e8?w=800&auto=format&fit=crop&q=80",
        "description": "Double-wall 18/8 food-grade stainless steel thermal bottle keeping liquids ice cold for 24 hours or piping hot for 12 hours. Sweat-free powder coat finish with silicone base guard and wide-mouth straw lid.",
    },

    # --- Category 8: Wellness & Grooming (Solace Botanicals) ---
    {
        "name": "Solace Radiance Botanical Face Nectar",
        "slug": "solace-radiance-botanical-face-nectar",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 68.00,
        "rating": 4.94,
        "stock_quantity": 50,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80",
        "description": "Nutrient-dense cold-pressed facial oil packed with organic rosehip, sea buckthorn, squalane, and CoQ10. Restores lipid moisture barrier, soothes redness, and imparts a natural luminous complexion.",
    },
    {
        "name": "Solace Mineral Dew Sunscreen SPF 50",
        "slug": "solace-mineral-dew-sunscreen-spf-50",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 34.00,
        "rating": 4.81,
        "stock_quantity": 80,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1598440947619-2c35fc9aa908?w=800&auto=format&fit=crop&q=80",
        "description": "100% non-nano zinc oxide broad spectrum mineral sunscreen with niacinamide, aloe vera, and green tea antioxidants. Zero white cast, water-resistant for 80 minutes, reef-safe, and non-comedogenic.",
    },
    {
        "name": "Solace Bamboo Charcoal Clarifying Soap Bar",
        "slug": "solace-bamboo-charcoal-clarifying-soap-bar",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 14.00,
        "rating": 4.75,
        "stock_quantity": 140,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1607006314592-969472304910?w=800&auto=format&fit=crop&q=80",
        "description": "Cold-process artisan bar soap infused with activated bamboo charcoal, tea tree, and unrefined shea butter. Gently detoxifies congested pores without stripping essential skin hydration.",
    },
    {
        "name": "Solace Weighted Linen Eye Pillow",
        "slug": "solace-weighted-linen-eye-pillow",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 28.00,
        "rating": 4.85,
        "stock_quantity": 65,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&auto=format&fit=crop&q=80",
        "description": "Hand-stitched Belgian linen eye mask filled with organic flaxseed and soothing French lavender buds. Can be heated or chilled to relieve eye fatigue, tension headaches, and facilitate deep meditation sleep.",
    },

    # --- Additional Products across categories to hit 50+ target ---
    {
        "name": "Aura SoundLink Bluetooth Transmitter",
        "slug": "aura-soundlink-bluetooth-transmitter",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 42.00,
        "rating": 4.6,
        "stock_quantity": 70,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800&auto=format&fit=crop&q=80",
        "description": "Airplane and gym equipment dual-link Bluetooth transmitter with aptX Low Latency. Connect your wireless headphones to in-flight entertainment screens or treadmills with zero sync delay.",
    },
    {
        "name": "Nordic Cable Management Under-Desk Tray",
        "slug": "nordic-cable-management-under-desk-tray",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 35.00,
        "rating": 4.75,
        "stock_quantity": 100,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1593062096033-9a26b09da705?w=800&auto=format&fit=crop&q=80",
        "description": "Steel wire raceway under-desk organizer for power bricks, extension cords, and monitors. Clamp-on installation with zero drilling required.",
    },
    {
        "name": "Apex Speed Jump Rope with Bearing System",
        "slug": "apex-speed-jump-rope-with-bearing-system",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 24.00,
        "rating": 4.8,
        "stock_quantity": 120,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
        "description": "Aircraft aluminum handles with 360-degree high-speed dual ball bearings and kink-free coated steel cable. Engineered for double-unders and boxing cardio workouts.",
    },
    {
        "name": "Origin Cold Brew Vacuum Pitcher 1.5L",
        "slug": "origin-cold-brew-vacuum-pitcher-15l",
        "business_slug": "origin-roastworks",
        "category_slug": "specialty-coffee-kitchen",
        "price": 45.00,
        "rating": 4.82,
        "stock_quantity": 50,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1517701550927-30cf4ba1dba5?w=800&auto=format&fit=crop&q=80",
        "description": "Borosilicate glass cold brew coffee maker with ultra-fine stainless steel mesh filter core and airtight silicone seal that fits in the refrigerator door.",
    },
    {
        "name": "Vanguard Modular Packing Cube Set (4-Piece)",
        "slug": "vanguard-modular-packing-cube-set-4-piece",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 42.00,
        "rating": 4.86,
        "stock_quantity": 85,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1581553680321-4fffae59fccd?w=800&auto=format&fit=crop&q=80",
        "description": "Ultra-lightweight compression travel packing cubes made from ripstop silnylon. Saves 40% luggage volume while keeping clean and dirty garments separated.",
    },
    {
        "name": "Lumina Smart LED Light Strip (6.5ft)",
        "slug": "lumina-smart-led-light-strip-65ft",
        "business_slug": "lumina-ambient-living",
        "category_slug": "smart-living",
        "price": 39.00,
        "rating": 4.7,
        "stock_quantity": 65,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1550684848-fac1c5b4e853?w=800&auto=format&fit=crop&q=80",
        "description": "Tunable white and 16-million color bias accent LED strip with cuttable segments and 3M adhesive backing for television backs, shelves, and desks.",
    },
    {
        "name": "Terra Titanium Camping Spork and Cutlery Tool",
        "slug": "terra-titanium-camping-spork-and-cutlery-tool",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 18.00,
        "rating": 4.88,
        "stock_quantity": 130,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1470246973918-29a93221c455?w=800&auto=format&fit=crop&q=80",
        "description": "Ultralight polished bowl titanium spork with matte handle and integrated bottle opener. Weighs only 16 grams for ultralight hikers.",
    },
    {
        "name": "Solace Deep Sleep Magnesium Body Butter",
        "slug": "solace-deep-sleep-magnesium-body-butter",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 32.00,
        "rating": 4.9,
        "stock_quantity": 70,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1608248597359-009710f63b8d?w=800&auto=format&fit=crop&q=80",
        "description": "Topical Zechstein pure magnesium chloride whipped with raw shea butter and chamomile to relax restless leg muscles and promote deep REM recovery.",
    },
    {
        "name": "Kanso Handcrafted Resin Wrist Rest",
        "slug": "kanso-handcrafted-resin-wrist-rest",
        "business_slug": "kanso-tech-lab",
        "category_slug": "workspace-tech",
        "price": 40.00,
        "rating": 4.82,
        "stock_quantity": 45,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1541140532154-b024d705b909?w=800&auto=format&fit=crop&q=80",
        "description": "Ergonomic keyboard wrist rest combining solid smoked oak with translucent emerald green epoxy resin. Polished silky smooth for fatigue-free typing.",
    },
    {
        "name": "Verdant Granite Mortar and Pestle (6-Inch)",
        "slug": "verdant-granite-mortar-and-pestle-6-inch",
        "business_slug": "verdant-culinary",
        "category_slug": "specialty-coffee-kitchen",
        "price": 48.00,
        "rating": 4.93,
        "stock_quantity": 35,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80",
        "description": "Heavy unpolished natural black granite molcajete for crushing whole peppercorns, fresh guacamole, chimichurri, and releasing essential aromatics.",
    },
    {
        "name": "Aura Horizon Portable Waterproof Bluetooth Speaker",
        "slug": "aura-horizon-portable-waterproof-bluetooth-speaker",
        "business_slug": "aura-acoustics",
        "category_slug": "audio-wearables",
        "price": 95.00,
        "rating": 4.81,
        "stock_quantity": 60,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800&auto=format&fit=crop&q=80",
        "description": "360-degree room-filling acoustic speaker with dual passive bass radiators, IP67 waterproof and floatable design, 20-hour battery, and PartySync linking.",
    },
    {
        "name": "Nordic Solid Birch Vertical Laptop Stand",
        "slug": "nordic-solid-birch-vertical-laptop-stand",
        "business_slug": "nordic-ergonomics",
        "category_slug": "workspace-tech",
        "price": 42.00,
        "rating": 4.77,
        "stock_quantity": 80,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1527443224154-c4a3942d3acf?w=800&auto=format&fit=crop&q=80",
        "description": "Gravity-locking vertical dock for MacBooks and laptops up to 16-inch. Frees up 80% desk surface area when working connected to external displays.",
    },
    {
        "name": "Apex Core Resistance Loop Bands Set of 5",
        "slug": "apex-core-resistance-loop-bands-set-of-5",
        "business_slug": "apex-kinetics",
        "category_slug": "fitness-activewear",
        "price": 19.00,
        "rating": 4.69,
        "stock_quantity": 150,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
        "description": "100% natural Malaysian latex exercise mini-bands in 5 progressive resistance levels (10 to 50 lbs) for physical therapy, glute activation, and home workouts.",
    },
    {
        "name": "Origin Double-Walled Glass Espresso Cups (Set of 2)",
        "slug": "origin-double-walled-glass-espresso-cups-set-of-2",
        "business_slug": "origin-roastworks",
        "category_slug": "specialty-coffee-kitchen",
        "price": 26.00,
        "rating": 4.88,
        "stock_quantity": 75,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
        "description": "Hand-blown thermal insulating borosilicate 3 oz glasses that keep espresso crema piping hot while remaining cool to the touch.",
    },
    {
        "name": "Vanguard Waxed Canvas Utility Roll Organiser",
        "slug": "vanguard-waxed-canvas-utility-roll-organiser",
        "business_slug": "vanguard-carry-goods",
        "category_slug": "bags-commute",
        "price": 34.00,
        "rating": 4.74,
        "stock_quantity": 65,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
        "description": "16 oz water-repellent Martexin waxed canvas tool and cable roll with 8 elasticated tool slots and leather wrap-around fastening strap.",
    },
    {
        "name": "Terra Solar Rechargeable LED Headlamp",
        "slug": "terra-solar-rechargeable-led-headlamp",
        "business_slug": "terra-wilds-equipment",
        "category_slug": "outdoors-expedition",
        "price": 38.00,
        "rating": 4.85,
        "stock_quantity": 85,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800&auto=format&fit=crop&q=80",
        "description": "500-lumen wide-angle flood and spot headlamp with red night-vision mode, USB-C fast charging, IPX6 waterproofing, and breathable reflective headband.",
    },
    {
        "name": "Solace Organic Cedarwood & Vetiver Beard Oil",
        "slug": "solace-organic-cedarwood-vetiver-beard-oil",
        "business_slug": "solace-botanicals",
        "category_slug": "wellness-grooming",
        "price": 26.00,
        "rating": 4.78,
        "stock_quantity": 90,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80",
        "description": "Conditioning blend of golden jojoba, argan, and Moroccan cedarwood essential oils. Softens coarse facial hair and hydrates underlying skin.",
    },
    {
        "name": "Kanso Low-Profile PBT Keycap Set (Retro Beige)",
        "slug": "kanso-low-profile-pbt-keycap-set-retro-beige",
        "business_slug": "kanso-tech-lab",
        "category_slug": "workspace-tech",
        "price": 49.00,
        "rating": 4.9,
        "stock_quantity": 40,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
        "description": "135-key thick dye-sublimated PBT keycap set in vintage computer workstation grey and beige. Compatible with standard MX mechanical switch stems.",
    },
    {
        "name": "Verdant End-Grain Teak Cutting Board",
        "slug": "verdant-end-grain-teak-cutting-board",
        "business_slug": "verdant-culinary",
        "category_slug": "specialty-coffee-kitchen",
        "price": 89.00,
        "rating": 4.96,
        "stock_quantity": 22,
        "stock_status": "in_stock",
        "image_url": "https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=800&auto=format&fit=crop&q=80",
        "description": "Substantial 18x14x1.5-inch end-grain sustainable teak butcher block with deep juice groove and inset hand grips. Gentle on premium knife edges.",
    },
]

# 16 Business Feed Posts
FEED_POSTS: List[Dict[str, Any]] = [
    {
        "business_slug": "aura-acoustics",
        "type": "product_launch",
        "title": "Introducing the Aura Flow ANC: Zero Compromise Audio",
        "content": "Two years in development, the Aura Flow brings beryllium studio drivers and next-generation hybrid noise-cancelling to daily commuters and fitness athletes alike. Now shipping worldwide.",
        "image_url": "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "nordic-ergonomics",
        "type": "article",
        "title": "The Ergonomics of Focus: How Sit-Stand Rhythms Boost Engineering Velocity",
        "content": "Our in-house biomechanical research team outlines the 20-8-2 formula: 20 minutes sitting upright, 8 minutes standing, and 2 minutes of active movement for maximum cognitive stamina.",
        "image_url": "https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "origin-roastworks",
        "type": "announcement",
        "title": "Direct Trade Harvest Arrives: Fresh Ethiopian Yirgacheffe",
        "content": "We just received our direct-trade green coffee shipment from the Gedeo zone in Ethiopia. Expect delicate jasmine floral aromatics and a clean honey finish. Roasting begins this Thursday.",
        "image_url": "https://images.unsplash.com/photo-1509785307050-d4066910ec1e?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "apex-kinetics",
        "type": "promotion",
        "title": "Spring Athletic Gear Refresh: 15% Off Activewear",
        "content": "Gear up for your upcoming marathon block. Enjoy 15% off all AeroFlex tights and Pace running footwear this week with code PACE15 at checkout.",
        "image_url": "https://images.unsplash.com/photo-1517838277536-f5f99be501cd?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "vanguard-carry-goods",
        "type": "update",
        "title": "Field Testing the Shift 26L in Tokyo and Reykjavik",
        "content": "Our design directors spent the last month field-testing the newly reinforced 840D Cordura seams through monsoon rain and sub-zero train commutes. All zippers held 100% water seal.",
        "image_url": "https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "lumina-ambient-living",
        "type": "article",
        "title": "Circadian Lighting: Why Blue Light Spectrum Timing Matters",
        "content": "Discover how transitioning from 6500K bright daylight at 10 AM to 2200K amber warm light at 8 PM optimizes evening melatonin release and improves deep slow-wave sleep.",
        "image_url": "https://images.unsplash.com/photo-1507473885765-e6ed057f782c?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "kanso-tech-lab",
        "type": "product_launch",
        "title": "Batch 3 of the Kanso 75 CNC Keyboard is Live",
        "content": "Each chassis is milled from a solid 4.2 lb block of 6063 aerospace aluminum with an anodized bead-blasted finish. Limited to 250 numbered units.",
        "image_url": "https://images.unsplash.com/photo-1587829741301-dc798b83add3?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "terra-wilds-equipment",
        "type": "announcement",
        "title": "Leave No Trace Partner Certification Achieved",
        "content": "Terra Wilds is proud to announce our official partner status with Leave No Trace. 1% of every titanium cookware sale goes towards trail restoration in Colorado wilderness areas.",
        "image_url": "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "verdant-culinary",
        "type": "article",
        "title": "How to Season and Maintain Your Cast Iron Skillet for Generations",
        "content": "Forget harsh detergents. Read our master bladesmith and cookware guide on polymerizing flaxseed oil at 450°F to create an indestructible non-stick patina.",
        "image_url": "https://images.unsplash.com/photo-1584990347449-399d8d641ea5?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "solace-botanicals",
        "type": "update",
        "title": "Zero-Waste Packaging Transition Complete",
        "content": "Every Solace formulation now ships in 100% post-consumer recycled violet glass bottles with aluminum dropper tops and seeded wildflower compostable boxes.",
        "image_url": "https://images.unsplash.com/photo-1556228720-195a672e8a03?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "aura-acoustics",
        "type": "promotion",
        "title": "Studio Bundle Promotion: Free Pocket DAC with Monitor Pair",
        "content": "Elevate your audio editing suite. Purchase a pair of Studio Reference One monitors and receive our Pocket DAC Amp free of charge through end of month.",
        "image_url": "https://images.unsplash.com/photo-1545454675-3531b543be5d?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "origin-roastworks",
        "type": "article",
        "title": "Dialing in Espresso: Flow Rate, Ratio, and Temperature Science",
        "content": "Learn why changing your water temperature by just 2°F dramatically impacts chlorogenic acid breakdown and sweetness extraction.",
        "image_url": "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "apex-kinetics",
        "type": "announcement",
        "title": "Welcoming Olympic Marathoner Elena Ramos to the Apex Roster",
        "content": "Elena will be training in the Apex Pace Carbon shoes for the upcoming Olympic trials in Paris. Check out her weekly workout breakdown on our feed.",
        "image_url": "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "vanguard-carry-goods",
        "type": "product_launch",
        "title": "The Tech Sling 7L is Back in Stock",
        "content": "Following our sold-out initial drop, the waterproof YKK Aquaguard Tech Sling is back with reinforced strap stitching and an updated tablet pocket lining.",
        "image_url": "https://images.unsplash.com/photo-1622560480605-d83c853bc5c3?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "nordic-ergonomics",
        "type": "update",
        "title": "New Solid American Walnut Desktop Options",
        "content": "Due to overwhelming demand from our design community, the Ergo-Lift desk is now available in sustainably harvested American Walnut.",
        "image_url": "https://images.unsplash.com/photo-1544816155-12df9643f363?w=800&auto=format&fit=crop&q=80",
    },
    {
        "business_slug": "terra-wilds-equipment",
        "type": "promotion",
        "title": "Expedition Ready Pack Bundle",
        "content": "Bundle any Alpine Ultralight Tent with the Titanium Solo Stove and receive a free Titanium Spork and stuff sack.",
        "image_url": "https://images.unsplash.com/photo-1510312305653-8ed496efae75?w=800&auto=format&fit=crop&q=80",
    },
]

# Demo User Profile
DEMO_USER = {
    "id": "a1000000-0000-0000-0000-000000000001",
    "name": "Alex Rivera",
    "email": "alex.rivera@example.com",
    # bcrypt hash for "ZentroDemo2026!"
    "password_hash": "$2b$12$0e3Zp0T38hQ2VbK0W.Xj..uG73l68l3hLpMvT/7951x61lQvDcmkG",
    "is_active": True,
}
